apiVersion: v1
kind: Service
metadata:
  name: angular-service
spec:
  type: NodePort
  ports:
    - port: 80          # Update to match the Nginx port inside the container
      targetPort: 80     # The container's internal port that Nginx listens to
      nodePort: 30000    # The external port to access the service
      protocol: TCP
  selector:
    app: angular-app
